modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/better-durability/issues"

[[mods]]
modId = "betterdurability"
version = "${file.jarVersion}"
displayName = "Better Durability"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/better-durability"
logoFile = "betterdurability.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
description = '''A mod to prevent your precious tools from breaking!'''